//! The HTTPS side of machine domains: a Caddy reverse proxy, driven the same
//! way gvproxy is — an external binary found on the PATH, configured and
//! supervised by bsdkrun.
//!
//! Caddy earns its place by doing the three hard parts at once: TLS
//! termination, per-domain certificates from a built-in local CA, and trust
//! store installation on both macOS (keychain) and Linux (system + NSS) via
//! `caddy trust` — all machinery bsdkrun would otherwise have to grow itself.
//!
//! Everything Caddy owns lives under `<state>/proxy/` — config, logs, admin
//! socket, and its PKI storage — so `domains disable --purge` removes it
//! completely and a system-level Caddy is never touched. The admin endpoint is
//! a unix socket, not the default 127.0.0.1:2019, for the same reason.

use std::path::PathBuf;
use std::process::{Command, Stdio};
use std::time::Duration;

use anyhow::{bail, Context, Result};
use tracing::warn;

use crate::{api, db};

use super::{dns_labels, Settings};

/// Find the caddy binary: explicit override, then PATH — the gvproxy pattern.
pub fn locate() -> Result<PathBuf> {
    if let Ok(p) = std::env::var("BSDKRUN_CADDY") {
        let p = PathBuf::from(p);
        if p.is_file() {
            return Ok(p);
        }
        bail!(
            "BSDKRUN_CADDY points at {}, which does not exist",
            p.display()
        );
    }
    let out = Command::new("/usr/bin/which").arg("caddy").output();
    if let Ok(o) = out {
        if o.status.success() {
            let path = String::from_utf8_lossy(&o.stdout).trim().to_string();
            if !path.is_empty() {
                return Ok(PathBuf::from(path));
            }
        }
    }
    bail!(
        "caddy not found on PATH. It terminates TLS for machine domains — install it with \
         `brew install caddy` (macOS) or `apt install caddy` (Linux), or set BSDKRUN_CADDY."
    )
}

/// The directory holding everything Caddy: Caddyfile, log, admin socket, PKI.
pub fn proxy_dir() -> Result<PathBuf> {
    Ok(db::state_dir()?.join("proxy"))
}

fn caddyfile_path() -> Result<PathBuf> {
    Ok(proxy_dir()?.join("Caddyfile"))
}

fn admin_socket() -> Result<PathBuf> {
    // Not in the state dir: sockaddr_un caps socket paths (~104 bytes on
    // macOS) and the state dir can be arbitrarily long ($BSDKRUN_STATE).
    // The temp dir is short on both OSes; the FNV hash of the state dir keeps
    // two bsdkrun instances with different state dirs from sharing a Caddy.
    let state = db::state_dir()?;
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for b in state.as_os_str().as_encoded_bytes() {
        hash ^= u64::from(*b);
        hash = hash.wrapping_mul(0x100_0000_01b3);
    }
    Ok(std::env::temp_dir().join(format!("bsdkrun-caddy-{hash:016x}.sock")))
}

/// `unix//<abs path>` — Caddy's syntax for a unix-socket admin address.
fn admin_address() -> Result<String> {
    Ok(format!("unix/{}", admin_socket()?.display()))
}

/// Render the Caddyfile for the current machine list. Deterministic, so `sync`
/// can compare bytes and skip the reload when nothing changed.
///
/// Every named machine with at least one port forward gets a site; stopped
/// machines are included deliberately — Caddy's 502 tells the user "known
/// machine, not running", where NXDOMAIN would say "never heard of it".
pub fn render_caddyfile(machines: &[api::Machine], s: &Settings) -> Result<String> {
    let dir = proxy_dir()?;
    let mut out = format!(
        "# Generated by bsdkrun — do not edit. `bsdkrun domains sync` regenerates it.\n\
         {{\n\
         \tadmin {admin}\n\
         \tskip_install_trust\n\
         \tstorage file_system {{\n\
         \t\troot {root}\n\
         \t}}\n\
         \thttp_port {http}\n\
         \thttps_port {https}\n\
         \tlocal_certs\n\
         }}\n",
        admin = admin_address()?,
        root = dir.join("data").display(),
        http = s.http_port,
        https = s.https_port,
    );
    for (label, m) in dns_labels(machines) {
        let Some(pf) = m.ports.first() else { continue };
        out.push_str(&format!(
            "\n# {} ({})\n{}.{} {{\n\treverse_proxy 127.0.0.1:{}\n}}\n",
            m.id,
            m.name.as_deref().unwrap_or("-"),
            label,
            s.tld,
            pf.host,
        ));
    }
    Ok(out)
}

/// Write the Caddyfile if its bytes changed. Returns whether it did.
pub fn write_caddyfile(contents: &str) -> Result<bool> {
    let path = caddyfile_path()?;
    std::fs::create_dir_all(proxy_dir()?)?;
    if std::fs::read_to_string(&path)
        .map(|c| c == contents)
        .unwrap_or(false)
    {
        return Ok(false);
    }
    std::fs::write(&path, contents).with_context(|| format!("writing {}", path.display()))?;
    Ok(true)
}

/// Spawn Caddy as a detached daemon (setsid, stderr → caddy.log, pid in
/// settings) and wait for its admin socket — the network-gvproxy pattern.
pub fn spawn(db: &db::Db) -> Result<u32> {
    use std::os::unix::process::CommandExt;
    let bin = locate()?;
    let dir = proxy_dir()?;
    std::fs::create_dir_all(&dir)?;
    let sock = admin_socket()?;
    let _ = std::fs::remove_file(&sock);
    let log_path = dir.join("caddy.log");
    let log = std::fs::File::create(&log_path)
        .with_context(|| format!("creating {}", log_path.display()))?;
    let mut cmd = Command::new(&bin);
    cmd.arg("run")
        .arg("--config")
        .arg(caddyfile_path()?)
        .arg("--adapter")
        .arg("caddyfile")
        .stdin(Stdio::null())
        .stdout(Stdio::null())
        .stderr(log);
    unsafe {
        cmd.pre_exec(|| {
            libc::setsid();
            Ok(())
        });
    }
    let child = cmd
        .spawn()
        .with_context(|| format!("spawning caddy ({})", bin.display()))?;
    let pid = child.id();
    std::mem::forget(child);
    db.set_setting("domains.caddy_pid", &pid.to_string())?;

    for _ in 0..50 {
        if sock.exists() {
            return Ok(pid);
        }
        std::thread::sleep(Duration::from_millis(100));
    }
    bail!(
        "caddy did not create its admin socket in time (see {}) — is another process \
         holding the HTTPS port? Try `--https-port 8443 --http-port 8080` on enable.",
        log_path.display(),
    )
}

/// Is the recorded Caddy alive (pid + admin socket)?
pub fn running(db: &db::Db) -> Result<bool> {
    let alive = db
        .get_setting("domains.caddy_pid")?
        .and_then(|p| p.parse::<i64>().ok())
        .map(db::pid_alive)
        .unwrap_or(false);
    Ok(alive && admin_socket()?.exists())
}

/// Zero-downtime reload of the current Caddyfile; falls back to kill+respawn
/// when the admin socket is gone.
pub fn reload(db: &db::Db) -> Result<()> {
    if running(db)? {
        let out = Command::new(locate()?)
            .arg("reload")
            .arg("--config")
            .arg(caddyfile_path()?)
            .arg("--adapter")
            .arg("caddyfile")
            .arg("--address")
            .arg(admin_address()?)
            .output()
            .context("running caddy reload")?;
        if out.status.success() {
            return Ok(());
        }
        warn!(
            stderr = %String::from_utf8_lossy(&out.stderr).trim(),
            "caddy reload failed; respawning"
        );
        stop(db)?;
    }
    spawn(db).map(|_| ())
}

/// Respawn Caddy if it died — lazy supervision for the sync hook.
pub fn ensure_running(db: &db::Db) -> Result<()> {
    if running(db)? {
        return Ok(());
    }
    spawn(db).map(|_| ())
}

/// SIGTERM the recorded Caddy, if any, and clear its pid.
pub fn stop(db: &db::Db) -> Result<()> {
    if let Some(pid) = db
        .get_setting("domains.caddy_pid")?
        .and_then(|p| p.parse::<i32>().ok())
    {
        if db::pid_alive(pid as i64) {
            unsafe { libc::kill(pid, libc::SIGTERM) };
        }
    }
    db.remove_setting("domains.caddy_pid")
}

/// Install Caddy's root CA into the system trust store(s). Inherits stdio —
/// `caddy trust` may prompt (macOS keychain auth, Linux sudo), and hiding that
/// prompt would hang silently.
pub fn trust() -> Result<()> {
    let status = Command::new(locate()?)
        .arg("trust")
        .arg("--address")
        .arg(admin_address()?)
        .status()
        .context("running caddy trust")?;
    if !status.success() {
        bail!(
            "`caddy trust` failed. On Linux, NSS-based browsers need `libnss3-tools` \
             installed for browser trust; re-run `bsdkrun domains enable` after installing."
        );
    }
    Ok(())
}

/// Remove the CA from the trust store(s). Best-effort — the CA files
/// themselves live in our storage root and go with `--purge`.
pub fn untrust() {
    if let Ok(bin) = locate() {
        let mut cmd = Command::new(bin);
        cmd.arg("untrust");
        // Point at the root cert on disk so untrust works even when the
        // daemon is already stopped.
        if let Ok(root) = ca_root_path() {
            if root.exists() {
                cmd.arg("--cert").arg(root);
            }
        }
        let _ = cmd.status();
    }
}

/// Caddy's local-CA root certificate inside our isolated storage root.
pub fn ca_root_path() -> Result<PathBuf> {
    Ok(proxy_dir()?.join("data/pki/authorities/local/root.crt"))
}

/// Is the local CA actually in the host trust store (not merely on disk)?
#[cfg(target_os = "macos")]
pub fn is_trusted() -> bool {
    Command::new("security")
        .args([
            "find-certificate",
            "-c",
            "Caddy Local Authority",
            "/Library/Keychains/System.keychain",
        ])
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// `openssl verify` against the installed bundle tests real trust, not just
/// that the CA file exists.
#[cfg(target_os = "linux")]
pub fn is_trusted() -> bool {
    let Ok(root) = ca_root_path() else {
        return false;
    };
    if !root.exists() {
        return false;
    }
    Command::new("openssl")
        .arg("verify")
        .args(["-CApath", "/etc/ssl/certs"])
        .arg(&root)
        .output()
        .map(|o| o.status.success())
        .unwrap_or(false)
}

/// Can this user bind the HTTPS port? On macOS low ports have been
/// unprivileged since 10.14; on Linux they need a one-time sysctl. Binding the
/// wildcard is the honest probe — that is what Caddy will do.
pub fn can_bind(port: u16) -> bool {
    std::net::TcpListener::bind(("0.0.0.0", port)).is_ok()
}

/// The one-time Linux fix for unprivileged 80/443, offered (not forced) on
/// enable: a sysctl.d drop-in applied immediately.
#[cfg(target_os = "linux")]
pub fn allow_low_ports() -> Result<()> {
    super::resolver::run_as_admin(
        "printf 'net.ipv4.ip_unprivileged_port_start=80\\n' \
         > /etc/sysctl.d/99-bsdkrun-unprivileged-ports.conf && sysctl --system",
    )
    .context("could not lower net.ipv4.ip_unprivileged_port_start")
}
