name: server
version: 0.1.0
license: MIT

dependencies:
  - base
  - bytestring
  - network

executables:
  server:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -O2
