// Package kraftfile generates a Kraftfile from a plan.Plan.
//
// The kconfig block below is the "library/base verbatim" section every
// examples/unikraft-*/Kraftfile in this repo carries — confirmed
// byte-identical across languages from Node to Rust — plus the small set of
// lines above it needed for libkrun specifically (PL011 console, FPSIMD,
// virtio-rng). Copied here verbatim (from examples/unikraft-expressjs's
// Kraftfile) rather than derived, so this is the one place that block lives
// as data instead of being hand-copied into a 21st example.
package kraftfile

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"text/template"

	"github.com/tsirysndr/bsdkrun/pack/internal/plan"
)

// GeneratedMarker identifies a Kraftfile pack wrote. `--clean` refuses to
// delete a Kraftfile without it, so a hand-written one — every unported
// examples/unikraft-* still has theirs — is never removed by mistake.
const GeneratedMarker = "# Generated by `bsdkrun pack`"

// The Unikraft refs every generated Kraftfile builds against.
//
// Pinned via the tsirysndr forks' `bsdkrun-stable` branches, never upstream
// `staging`: staging moved on 2026-08-12 (upstream 3898a16e36, "Handle
// _SC_CLK_TCK in sysconf()") and broke every build against its own headers —
// and kraft resolves refs, not raw SHAs, so the pin has to be a branch we
// control. `bsdkrun-stable` currently sits at ecf0fa174c5d (the breaking
// commit's parent) for unikraft and at the last green staging head for lwip.
// Bump by moving the branch on the fork, deliberately, with a passing build.
// The examples' hand-written Kraftfiles pin the same refs.
const (
	UnikraftSource  = "https://github.com/tsirysndr/unikraft.git"
	UnikraftVersion = "bsdkrun-stable"
	LwipSource      = "https://github.com/tsirysndr/lib-lwip.git"
	LwipVersion     = "bsdkrun-stable"
)

const tmpl = GeneratedMarker + ` — do not edit; regenerate instead.
#
# Anything you change here is overwritten on the next pack. To influence
# what lands in it, use railpack.json or the provider.
spec: v0.6

name: {{.Name}}

unikraft:
  source: ` + UnikraftSource + `
  version: ` + UnikraftVersion + `
  kconfig:
    # libkrun's aarch64 console is a PL011.
    CONFIG_LIBPL011: 'y'
    CONFIG_LIBPL011_EARLY_CONSOLE: 'y'

    # Let the application use FP/SIMD (arm64-only, default n — without it a
    # binary traps on its first NEON instruction about a second into boot).
    CONFIG_FPSIMD: 'y'

    # Entropy from the host over virtio-rng — needs the driver installed by
    # pack's embedded copy of library/unikraft-base/patches.
    CONFIG_LIBVIRTIO_RNG: 'y'

    # --- everything below is library/base's config, verbatim ---
    CONFIG_HAVE_PAGING_DIRECTMAP: 'y'
    CONFIG_HAVE_PAGING: 'y'
    CONFIG_I8042: 'y'
    CONFIG_LIBVIRTIO_MMIO: 'y'
    CONFIG_VIRTIO_MMIO_MAX_DEV_CMDLINE: '8'
    CONFIG_LIBDEVFS_AUTOMOUNT: 'y'
    CONFIG_LIBDEVFS_DEV_NULL: 'y'
    CONFIG_LIBDEVFS_DEV_STDOUT: 'y'
    CONFIG_LIBDEVFS_DEV_ZERO: 'y'
    CONFIG_LIBDEVFS: 'y'
    CONFIG_LIBPOSIX_ENVIRON: 'y'
    CONFIG_LIBPOSIX_ENVIRON_ENVP0: "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    CONFIG_LIBPOSIX_ENVIRON_ENVP1: "LD_LIBRARY_PATH=/usr/local/lib:/usr/lib:/lib"
    CONFIG_LIBPOSIX_ENVIRON_ENVP2: "HOME=/"
    CONFIG_LIBPOSIX_ENVIRON_ENVP3: "PWD=/"
    CONFIG_LIBPOSIX_ENVIRON_LIBPARAM: 'y'
    CONFIG_LIBPOSIX_EVENTFD: 'y'
    CONFIG_LIBPOSIX_FDIO: 'y'
    CONFIG_LIBPOSIX_FDTAB: 'y'
    CONFIG_LIBPOSIX_FUTEX: 'y'
    CONFIG_LIBPOSIX_MMAP: 'y'
    CONFIG_LIBPOSIX_NETLINK: 'y'
    CONFIG_LIBPOSIX_PIPE: 'y'
    CONFIG_LIBPOSIX_POLL: 'y'
    CONFIG_LIBPOSIX_PROCESS: 'y'
    CONFIG_LIBPOSIX_PROCESS_MULTITHREADING: 'y'
    # Deliver CPU faults to the application as signals, and give it a brk.
    # Base config, not a per-runtime tweak: 13 of the 17 hand-written
    # examples set both, and the ones that need them need them badly. The
    # JVM turns SIGSEGV into its implicit null check, so without delivery
    # the first null dereference is a fatal trap and the guest dies with a
    # register dump instead of an exception. OpenSSL's CPU probes expect
    # SIGILL back from an instruction they run on purpose. The cost to a
    # runtime that uses neither is nil.
    CONFIG_LIBPOSIX_PROCESS_SIGNAL: 'y'
    CONFIG_LIBPOSIX_PROCESS_BRK: 'y'
    CONFIG_LIBPOSIX_SOCKET: 'y'
    CONFIG_LIBPOSIX_SYSINFO: 'y'
    CONFIG_LIBPOSIX_TIME: 'y'
    CONFIG_LIBPOSIX_TIMERFD: 'y'
    CONFIG_LIBPOSIX_UNIXSOCKET: 'y'
    CONFIG_LIBPOSIX_USER_GID: 0
    CONFIG_LIBPOSIX_USER_GROUPNAME: "root"
    CONFIG_LIBPOSIX_USER_UID: 0
    CONFIG_LIBPOSIX_USER_USERNAME: "root"
    CONFIG_LIBPOSIX_USER: 'y'
    CONFIG_LIBRAMFS: 'y'
    CONFIG_LIBSYSCALL_SHIM_HANDLER_ULTLS: 'y'
    CONFIG_LIBSYSCALL_SHIM_HANDLER: 'y'
    CONFIG_LIBSYSCALL_SHIM_LEGACY_VERBOSE: 'y'
    CONFIG_LIBSYSCALL_SHIM_STRACE: '{{if .Strace}}y{{else}}n{{end}}'
    CONFIG_LIBSYSCALL_SHIM: 'y'
    CONFIG_LIBUKALLOCPOOL: 'y'
    CONFIG_LIBUKBLKDEV_SYNC_IO_BLOCKED_WAITING: 'y'
    CONFIG_LIBUKBLKDEV: 'y'
    CONFIG_LIBUKBOOT_BANNER_MINIMAL: 'y'
    CONFIG_LIBUKBOOT_HEAP_BASE: '0x400000000'
    CONFIG_LIBUKBOOT_MAINTHREAD: 'y'
    CONFIG_LIBUKBOOT_SHUTDOWNREQ_HANDLER: 'y'
    CONFIG_LIBUKLIBPARAM: 'y'
    CONFIG_LIBUKCPIO: 'y'
    CONFIG_LIBUKDEBUG_CRASH_SCREEN: 'y'
    CONFIG_LIBUKDEBUG_ENABLE_ASSERT: 'y'
    CONFIG_LIBUKDEBUG_PRINT_SRCNAME: 'n'
    CONFIG_LIBUKDEBUG_PRINT_TIME: 'y'
    CONFIG_LIBUKDEBUG_PRINTK_ERR: 'y'
    CONFIG_LIBUKDEBUG_PRINTK: 'y'
    CONFIG_LIBUKDEBUG: 'y'
    CONFIG_LIBUKFALLOC: 'y'
    CONFIG_LIBUKMPI: 'n'
    CONFIG_LIBUKSIGNAL: 'y'
    CONFIG_LIBUKRANDOM_DEVFS: 'y'
    CONFIG_LIBUKRANDOM: 'y'
    CONFIG_LIBUKRANDOM_GETRANDOM: 'y'
    CONFIG_LIBUKRANDOM_CMDLINE_SEED: 'y'
    CONFIG_LIBUKRANDOM_LCPU: 'y'
    CONFIG_LIBUKVMEM_DEFAULT_BASE: '0x0000001000000000'
    CONFIG_LIBUKVMEM_DEMAND_PAGE_IN_SIZE: 12
    CONFIG_LIBUKVMEM_PAGEFAULT_HANDLER_PRIO: 4
    CONFIG_LIBUKVMEM: 'y'
    CONFIG_LIBVFSCORE_AUTOMOUNT_CI_EINITRD: 'y'
    CONFIG_LIBVFSCORE_AUTOMOUNT_CI: 'y'
    CONFIG_LIBVFSCORE_AUTOMOUNT_FB: 'y'
    CONFIG_LIBVFSCORE_AUTOMOUNT_FB0_DEV: "embedded"
    CONFIG_LIBVFSCORE_AUTOMOUNT_FB0_DRIVER: "extract"
    CONFIG_LIBVFSCORE_AUTOMOUNT_FB0_MP: "/"
    CONFIG_LIBVFSCORE_AUTOMOUNT_UP: 'y'
    CONFIG_LIBVFSCORE_AUTOMOUNT: 'y'
    CONFIG_LIBVFSCORE_NONLARGEFILE: 'y'
    CONFIG_LIBVFSCORE: 'y'
    CONFIG_LIBUK9P: 'y'
    CONFIG_OPTIMIZE_DEADELIM: 'y'
    CONFIG_OPTIMIZE_LTO: 'y'
    CONFIG_PAGING: 'y'
    CONFIG_STACK_SIZE_PAGE_ORDER: 4
    CONFIG_UKPLAT_KSP_SIZE: 32768
    CONFIG_UKPLAT_MEMREGION_MAX_COUNT: 64
    CONFIG_LIBUKNETDEV: 'y'
    CONFIG_LIBUKNETDEV_EINFO_LIBPARAM: 'y'
{{- range .KconfigKeys}}
    {{.}}: {{index $.Kconfig .}}
{{- end}}

libraries:
  # A Rust rewrite of upstream app-elfloader. It keeps upstream's Kconfig
  # surface exactly, which is why every symbol below is unchanged from the
  # stock elfloader configuration.
  app-elfloader:
    source: https://github.com/tsirysndr/app-elfloader.git
    version: main
    kconfig:
{{- range .ElfloaderKeys}}
      {{.}}: {{index $.ElfloaderKconfig .}}
{{- end}}
  lwip:
    source: ` + LwipSource + `
    version: ` + LwipVersion + `
    kconfig:
      CONFIG_LWIP_LOOPIF: 'y'
      CONFIG_LWIP_UKNETDEV: 'y'
      CONFIG_LWIP_LOOPBACK: 'y'
      CONFIG_LWIP_TCP: 'y'
      CONFIG_LWIP_UDP: 'y'
      CONFIG_LWIP_RAW: 'y'
      CONFIG_LWIP_WND_SCALE: 'y'
      CONFIG_LWIP_TCP_KEEPALIVE: 'y'
      CONFIG_LWIP_THREADS: 'y'
      CONFIG_LWIP_HEAP: 'y'
      CONFIG_LWIP_SOCKET: 'y'
      CONFIG_LWIP_AUTOIFACE: 'y'
      CONFIG_LWIP_IPV4: 'y'
      CONFIG_LWIP_DHCP: 'y'
      CONFIG_LWIP_WAITIFACE: 'y'
      CONFIG_LWIP_DNS: 'n'
      CONFIG_LWIP_NUM_TCPCON: 64
      CONFIG_LWIP_NUM_TCPLISTENERS: 64
      CONFIG_LWIP_ICMP: 'y'

targets:
- fc/arm64
- fc/x86_64

cmd: [{{range $i, $c := .Cmd}}{{if $i}}, {{end}}{{printf "%q" $c}}{{end}}]
`

var parsed = template.Must(template.New("Kraftfile").Parse(tmpl))

type data struct {
	Name             string
	Cmd              []string
	Kconfig          map[string]string
	KconfigKeys      []string // sorted, so output is deterministic
	ElfloaderKconfig map[string]string
	ElfloaderKeys    []string
	Strace           bool
	LoaderDebug      bool
}

// elfloaderDefaults is app-elfloader's kconfig as every hand-written example
// carries it. A provider overrides individual entries (Bun needs a 16x
// bigger stack, say) via Plan.ElfloaderKconfig rather than restating the
// whole block.
var elfloaderDefaults = map[string]string{
	// Implements arch_prctl(ARCH_SET_FS), how glibc installs the thread
	// pointer on x86_64; without it startup dies before main.
	"CONFIG_LIBPOSIX_PROCESS_ARCH_PRCTL":              "'y'",
	"CONFIG_APPELFLOADER_CUSTOMAPPNAME":               "'y'",
	"CONFIG_APPELFLOADER_STACK_NBPAGES":               "128",
	"CONFIG_APPELFLOADER_VFSEXEC":                     "'y'",
	"CONFIG_APPELFLOADER_VFSEXEC_EXECBIT":             "'y'",
	"CONFIG_APPELFLOADER_VFSEXEC_ENVPWD":              "'y'",
	"CONFIG_APPELFLOADER_VFSEXEC_ENVPATH":             "'y'",
	"CONFIG_APPELFLOADER_AUTOGEN":                     "'y'",
	"CONFIG_APPELFLOADER_AUTOGEN_ETCRESOLVCONF":       "'y'",
	"CONFIG_APPELFLOADER_AUTOGEN_ETCHOSTS":            "'y'",
	"CONFIG_APPELFLOADER_AUTOGEN_ETCHOSTS_LOCALHOST4": "'y'",
	"CONFIG_APPELFLOADER_AUTOGEN_ETCHOSTNAME":         "'y'",
	"CONFIG_APPELFLOADER_AUTOGEN_REPLACEEXIST":        "'y'",
}

// Options are Kraftfile-generation choices that come from the `pack`
// invocation itself rather than from the detected plan. Both default to
// `false`: each is invaluable for debugging a guest that boots but doesn't
// behave, and each is very noisy and slows the boot down (the same tradeoff
// the hand-written examples' Kraftfiles already document for these symbols).
type Options struct {
	Strace bool

	// LoaderDebug turns on app-elfloader's placement trace
	// (CONFIG_APPELFLOADER_DEBUG). Unlike Strace — which only shows
	// syscalls the application makes, so it says nothing at all about a
	// guest that dies before its first one — this prints while the loader
	// is still mapping the binary, which is what distinguishes "never
	// loaded" from "loaded, then died at the entry point".
	LoaderDebug bool
}

// Generate renders p's Kraftfile.
func Generate(p *plan.Plan, opts Options) (string, error) {
	applyGuestEnv(p)

	keys := make([]string, 0, len(p.Kconfig))
	for k := range p.Kconfig {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	// Defaults first, then the provider's overrides on top.
	elf := make(map[string]string, len(elfloaderDefaults))
	for k, v := range elfloaderDefaults {
		elf[k] = v
	}
	for k, v := range p.ElfloaderKconfig {
		elf[k] = v
	}
	elf["CONFIG_APPELFLOADER_DEBUG"] = "'n'"
	if opts.LoaderDebug {
		elf["CONFIG_APPELFLOADER_DEBUG"] = "'y'"
	}
	elfKeys := make([]string, 0, len(elf))
	for k := range elf {
		elfKeys = append(elfKeys, k)
	}
	sort.Strings(elfKeys)

	var buf bytes.Buffer
	err := parsed.Execute(&buf, data{
		Name:             p.Name,
		Cmd:              p.Cmd,
		Kconfig:          p.Kconfig,
		KconfigKeys:      keys,
		ElfloaderKconfig: elf,
		ElfloaderKeys:    elfKeys,
		Strace:           opts.Strace,
		LoaderDebug:      opts.LoaderDebug,
	})
	if err != nil {
		return "", fmt.Errorf("rendering Kraftfile: %w", err)
	}
	return overrideBaseKconfig(buf.String(), keys), nil
}

// baseEnvpCount is how many ENVP entries the base kconfig block defines
// (ENVP0..ENVP3: PATH, LD_LIBRARY_PATH, HOME, PWD).
const baseEnvpCount = 4

// applyGuestEnv turns the project's deploy.variables into ENVP entries.
//
// The indices have to be allocated rather than fixed: providers already
// claim them from ENVP4 up — beam takes 4 through 7, gleam 8 and 9 — so a
// project variable written to a fixed offset would silently overwrite
// ROOTDIR or BINDIR and break the guest in a way that looks nothing like a
// config mistake. This starts after the highest index anyone has taken.
//
// A variable that names one the provider or the base block already set
// replaces it in place, so a project can override PATH without ending up
// with two PATH entries and no say in which wins.
func applyGuestEnv(p *plan.Plan) {
	if len(p.GuestEnv) == 0 {
		return
	}
	if p.Kconfig == nil {
		p.Kconfig = map[string]string{}
	}

	// Where each name currently lives, and the first free index.
	at := map[string]string{}
	next := baseEnvpCount
	for key, value := range p.Kconfig {
		idx, ok := envpIndex(key)
		if !ok {
			continue
		}
		if idx >= next {
			next = idx + 1
		}
		if name, _, found := strings.Cut(strings.Trim(value, `"`), "="); found {
			at[name] = key
		}
	}
	for i, name := range baseEnvpNames {
		if _, taken := at[name]; !taken {
			at[name] = fmt.Sprintf("CONFIG_LIBPOSIX_ENVIRON_ENVP%d", i)
		}
	}

	names := make([]string, 0, len(p.GuestEnv))
	for name := range p.GuestEnv {
		names = append(names, name)
	}
	sort.Strings(names) // deterministic output

	for _, name := range names {
		key, exists := at[name]
		if !exists {
			key = fmt.Sprintf("CONFIG_LIBPOSIX_ENVIRON_ENVP%d", next)
			next++
		}
		p.Kconfig[key] = strconv.Quote(name + "=" + p.GuestEnv[name])
	}
}

// baseEnvpNames are the variables the base kconfig block sets, in index
// order, so that overriding one replaces it rather than adding a duplicate.
var baseEnvpNames = []string{"PATH", "LD_LIBRARY_PATH", "HOME", "PWD"}

// envpIndex reads the N out of CONFIG_LIBPOSIX_ENVIRON_ENVP<N>.
func envpIndex(key string) (int, bool) {
	const prefix = "CONFIG_LIBPOSIX_ENVIRON_ENVP"
	rest, ok := strings.CutPrefix(key, prefix)
	if !ok {
		return 0, false
	}
	idx, err := strconv.Atoi(rest)
	if err != nil {
		return 0, false
	}
	return idx, true
}

// overrideBaseKconfig drops a base kconfig line when a provider set the same
// symbol, so the provider's value is the only one left.
//
// Needed because the base block is written out verbatim — its per-line
// comments carry why each symbol is set, which is worth keeping — while
// providers append theirs afterwards. A symbol in both would appear twice,
// and a duplicate mapping key is at best last-wins and at worst a parse
// error. The Clojure provider hits this: it has to point LD_LIBRARY_PATH at
// the jlink'd JRE, replacing the base ENVP1 rather than adding to it.
func overrideBaseKconfig(rendered string, overridden []string) string {
	for _, key := range overridden {
		prefix := "    " + key + ":"
		lines := strings.Split(rendered, "\n")
		last := -1
		count := 0
		for i, l := range lines {
			if strings.HasPrefix(l, prefix) {
				count++
				last = i
			}
		}
		if count < 2 {
			continue
		}
		kept := make([]string, 0, len(lines))
		for i, l := range lines {
			if strings.HasPrefix(l, prefix) && i != last {
				continue
			}
			kept = append(kept, l)
		}
		rendered = strings.Join(kept, "\n")
	}
	return rendered
}

// Write renders p's Kraftfile and writes it to dir/Kraftfile.
//
// Deliberately no `rootfs:` field: every caller of internal/kraft passes
// `kraft build --rootfs <dir>` explicitly (mirroring build.sh), so the field
// would never be consulted — and unlike the hand-written examples, which
// point it at a Dockerfile for a human reader, pack has no Dockerfile to
// point at.
func Write(dir string, p *plan.Plan, opts Options) error {
	content, err := Generate(p, opts)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "Kraftfile"), []byte(content), 0o644)
}
